// ── Transport Module — Type definitions ─────────────────────

export const TransportMode = {
	Road: 'Road',
	Cycle: 'Cycle',
	Metro: 'Metro',
	Train: 'Train',
} as const;
export type TransportMode = (typeof TransportMode)[keyof typeof TransportMode];

// ── Pop Archetype definitions ───────────────────────────────

/** Utility weights governing mode choice for a Pop archetype. */
export interface UtilityWeights {
	/** Weight for travel time (minutes). Negative = dislikes longer trips. */
	readonly timePenalty: number;
	/** Weight for monetary cost (currency units). */
	readonly costPenalty: number;
	/** Preference bonus for cycling (comfort/fitness). */
	readonly cyclePref: number;
	/** Preference bonus for public transit (metro/train). */
	readonly transitPref: number;
}

/** A single daily activity (trip origin→destination attractor). */
export interface DailyActivity {
	/** Hour of day (0–23) the trip starts. */
	readonly hour: number;
	/** Destination attractor type — maps to EntityType values. */
	readonly destination: string;
	/** Optional: return trip hour. If set, a reverse trip is generated. */
	readonly returnHour?: number;
}

/** Profile for one Pop archetype. */
export interface ArchetypeProfile {
	readonly name: string;
	/** Fraction of total population following this archetype (0–1). */
	readonly fraction: number;
	readonly weights: UtilityWeights;
	readonly schedule: readonly DailyActivity[];
}

// ── Network graph types ─────────────────────────────────────

/** Weight/cost for traversing an edge via a specific mode. */
export interface EdgeWeight {
	/** Minutes to traverse (based on distance and mode speed). */
	readonly timeMins: number;
	/** Monetary cost for this segment. */
	readonly cost: number;
}

/** A directed edge in the multi-modal transport graph. */
export interface TransportEdge {
	readonly from: number; // cell index
	readonly to: number;   // cell index
	/** Distance in metres between cell centers. */
	readonly distanceM: number;
	/** Available modes and their traversal costs. */
	readonly weights: Partial<Record<TransportMode, EdgeWeight>>;
}

// ── Routing types ───────────────────────────────────────────

/** A resolved route for a single mode from origin to destination. */
export interface ResolvedRoute {
	readonly mode: TransportMode;
	readonly path: number[]; // cell indices
	readonly totalTimeMins: number;
	readonly totalCost: number;
}

// ── Trip & flow types ───────────────────────────────────────

/** A single trip generated by the Pop scheduler. */
export interface Trip {
	readonly archetypeName: string;
	readonly originCell: number;
	readonly destCell: number;
	readonly hour: number;
	readonly mode: TransportMode;
	readonly route: number[]; // cell indices along path
	readonly timeMins: number;
}

/** Accumulated flow on a cell-to-cell edge segment. */
export interface FlowSegment {
	readonly from: number;
	readonly to: number;
	readonly mode: TransportMode;
	readonly tripsPerHour: number;
}

/** Occupancy per cell (how many trips pass through). */
export interface OccupancyRate {
	readonly cellIndex: number;
	readonly tripsPerHour: number;
}

// ── Module result (per-tick output) ─────────────────────────

export interface TransportResult {
	readonly trips: readonly Trip[];
	readonly segments: readonly FlowSegment[];
	readonly occupancy: readonly OccupancyRate[];
	readonly modalSplit: Readonly<Record<TransportMode, number>>;
	readonly avgCommuteMins: number;
	readonly totalPassengers: number;
	readonly congestionIndex: number;
}

// ── Visual edge data for renderer ───────────────────────────

export interface NetworkEdgeVisual {
	readonly fromX: number;
	readonly fromZ: number;
	readonly toX: number;
	readonly toZ: number;
	readonly mode: TransportMode;
	readonly flow: number; // trips per hour on this segment
}
